{{- if .Values.serviceAccount.create | default false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-app-1.serviceAccountName" . }}
  labels:
    {{- include "my-app-1.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}